version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '1337:1337'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    #password: root123
